-- 组织关联与基础设施画像相关表（新环境随 init 执行）

CREATE TABLE IF NOT EXISTS alert_domain_matches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    alert_id BIGINT UNSIGNED NOT NULL,
    task_id BIGINT UNSIGNED NULL,
    domain_id INT NULL,
    domain_name VARCHAR(255) NOT NULL,
    malicious_score DECIMAL(6,4) NULL,
    risk_level VARCHAR(32) NULL,
    matched_organization_id INT NULL,
    matched_organization_name VARCHAR(255) NULL,
    actor_score DECIMAL(6,4) NULL,
    actor_confidence VARCHAR(32) NULL,
    reason_summary TEXT NULL,
    evidence_json JSON NULL,
    top_candidates_json JSON NULL,
    enrichment_snapshot_json JSON NULL,
    model_id BIGINT UNSIGNED NULL,
    model_version VARCHAR(64) NULL,
    actor_profile_version VARCHAR(64) NULL,
    match_method VARCHAR(64) NOT NULL DEFAULT 'rule_v2_infra',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_alert_id (alert_id),
    INDEX idx_task_id (task_id),
    INDEX idx_domain_id (domain_id),
    INDEX idx_domain_name (domain_name),
    INDEX idx_matched_organization_id (matched_organization_id),
    INDEX idx_actor_score (actor_score),
    INDEX idx_model_id (model_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='预警域名组织关联结果表';

CREATE TABLE IF NOT EXISTS actor_infra_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    profile_key VARCHAR(128) NOT NULL,
    profile_type VARCHAR(32) NOT NULL,
    organization_id INT NULL,
    organization_name VARCHAR(255) NULL,
    profile_version INT NOT NULL DEFAULT 1,
    profile_status VARCHAR(32) NOT NULL DEFAULT 'active',
    domain_profile_json JSON NULL,
    whois_profile_json JSON NULL,
    dns_profile_json JSON NULL,
    ssl_profile_json JSON NULL,
    global_stats_json JSON NULL,
    summary_json JSON NULL,
    build_meta_json JSON NULL,
    source_domain_count INT NOT NULL DEFAULT 0,
    whois_record_count INT NOT NULL DEFAULT 0,
    dns_record_count INT NOT NULL DEFAULT 0,
    ssl_record_count INT NOT NULL DEFAULT 0,
    last_built_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_profile_key (profile_key),
    INDEX idx_profile_type (profile_type),
    INDEX idx_organization_id (organization_id),
    INDEX idx_profile_status (profile_status),
    INDEX idx_last_built_at (last_built_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='组织基础设施画像缓存表';
