import { defineEventHandler } from 'h3'

const menuData = [
  {
    id: 2,
    parentId: null,
    title: '分析页',
    icon: 'DashboardOutlined',
    component: '/dashboard/analysis',
    path: '/dashboard/analysis',
    name: 'DashboardAnalysis',
    keepAlive: true,
    locale: 'menu.dashboard.analysis',
  },
  {
    id: 1,
    parentId: null,
    title: '仪表盘',
    icon: 'RadarChartOutlined',
    component: 'RouteView',
    redirect: '/dashboard/analysis',
    path: '/dashboard',
    name: 'Dashboard',
    locale: 'menu.dashboard',
  },
  {
    id: 3,
    parentId: null,
    title: '检测任务',
    icon: 'FormOutlined',
    component: 'RouteView',
    redirect: '/detection/create-task',
    path: '/detection',
    name: 'detection',
    locale: 'menu.detection',
  },
  {
    id: 5,
    parentId: null,
    title: '链接',
    icon: 'LinkOutlined',
    component: 'RouteView',
    redirect: '/link/iframe',
    path: '/link',
    name: 'Link',
    locale: 'menu.link',

  },
  {
    id: 6,
    parentId: 5,
    title: 'AntDesign',
    url: 'https://ant.design/',
    component: 'Iframe',
    path: '/link/iframe',
    name: 'LinkIframe',
    keepAlive: true,
    locale: 'menu.link.iframe',
  },
  {
    id: 7,
    parentId: 5,
    title: 'AntDesignVue',
    url: 'https://antdv.com/',
    component: 'Iframe',
    path: '/link/antdv',
    name: 'LinkAntdv',
    keepAlive: true,
    locale: 'menu.link.antdv',
  },
  {
    id: 8,
    parentId: 5,
    path: 'https://www.baidu.com',
    name: 'LinkExternal',
    title: '跳转百度',
    locale: 'menu.link.external',
  },
  {
    id: 9,
    parentId: null,
    title: '模型管理',
    icon: 'BarsOutlined',
    component: 'RouteView',
    path: '/models',
    redirect: '/models/menu1',
    name: 'ModleManagement',
    locale: 'menu.models',
  },

  {
    id: 10,
    parentId: 9,
    title: '模型训练',
    component: '/models/model-training/index',
    path: '/models/model-training',
    name: 'ModelTraining',
    keepAlive: true,
    locale: 'menu.models.model-training',
  },
  {
    id: 11,
    parentId: 9,
    title: '模型市场',
    component: '/models/model-market/index',
    path: '/models/model-market',
    keepAlive: true,
    locale: 'menu.models.model-market',
  },
  {
    id: 12,
    parentId: 9,
    path: '/models/my-model',
    title: '我的模型',
    component: '/models/my-model/index',
    keepAlive: true,
    locale: 'menu.models.my-model',
  },
  /* {
    id: 13,
    parentId: 12,
    path: '/menu/my-model/menu1',
    component: '/menu/menu-1-1/menu1',
    title: '菜单1-1-1',
    keepAlive: true,
    locale: 'menu.my-model.menu1',
  },
  {
    id: 14,
    parentId: 12,
    path: '/menu/my-model/menu2',
    component: '/menu/menu-1-1/menu2',
    title: '菜单1-1-2',
    keepAlive: true,
    locale: 'menu.my-model.menu2',
  }, */
  {
    id: 19,
    parentId: null,
    title: '异常页',
    icon: 'WarningOutlined',
    component: 'RouteView',
    redirect: '/exception/403',
    path: '/exception',
    name: 'Exception',
    locale: 'menu.exception',
  },
  {
    id: 20,
    parentId: 19,
    path: '/exception/403',
    title: '403',
    name: '403',
    component: '/exception/403',
    locale: 'menu.exception.not-permission',
  },
  {
    id: 21,
    parentId: 19,
    path: '/exception/404',
    title: '404',
    name: '404',
    component: '/exception/404',
    locale: 'menu.exception.not-find',
  },
  {
    id: 22,
    parentId: 19,
    path: '/exception/500',
    title: '500',
    name: '500',
    component: '/exception/500',
    locale: 'menu.exception.server-error',
  },
  {
    id: 23,
    parentId: null,
    title: '结果页',
    icon: 'CheckCircleOutlined',
    component: 'RouteView',
    redirect: '/result/success',
    path: '/result',
    name: 'Result',
    locale: 'menu.result',
  },
  {
    id: 24,
    parentId: 23,
    path: '/result/success',
    title: '成功页',
    name: 'ResultSuccess',
    component: '/result/success',
    locale: 'menu.result.success',
  },
  {
    id: 25,
    parentId: 23,
    path: '/result/fail',
    title: '失败页',
    name: 'ResultFail',
    component: '/result/fail',
    locale: 'menu.result.fail',
  },
  {
    id: 26,
    parentId: null,
    title: '列表页',
    icon: 'TableOutlined',
    component: 'RouteView',
    redirect: '/list/card-list',
    path: '/list',
    name: 'List',
    locale: 'menu.list',
  },
  {
    id: 27,
    parentId: 26,
    path: '/list/card-list',
    title: '卡片列表',
    name: 'ListCard',
    component: '/list/card-list',
    locale: 'menu.list.card-list',
  },
  {
    id: 28,
    parentId: null,
    title: '详情页',
    icon: 'ProfileOutlined',
    component: 'RouteView',
    redirect: '/profile/basic',
    path: '/profile',
    name: 'Profile',
    locale: 'menu.profile',
  },
  {
    id: 29,
    parentId: 28,
    path: '/profile/basic',
    title: '基础详情页',
    name: 'ProfileBasic',
    component: '/profile/basic/index',
    locale: 'menu.profile.basic',
  },
  {
    id: 30,
    parentId: 26,
    path: '/list/search-list',
    title: '搜索列表',
    name: 'SearchList',
    component: '/list/search-list',
    locale: 'menu.list.search-list',
  },
  {
    id: 31,
    parentId: 30,
    path: '/list/search-list/articles',
    title: '搜索列表（文章）',
    name: 'SearchListArticles',
    component: '/list/search-list/articles',
    locale: 'menu.list.search-list.articles',
  },
  {
    id: 32,
    parentId: 30,
    path: '/list/search-list/projects',
    title: '搜索列表（项目）',
    name: 'SearchListProjects',
    component: '/list/search-list/projects',
    locale: 'menu.list.search-list.projects',
  },
  {
    id: 33,
    parentId: 30,
    path: '/list/search-list/applications',
    title: '搜索列表（应用）',
    name: 'SearchListApplications',
    component: '/list/search-list/applications',
    locale: 'menu.list.search-list.applications',
  },
  {
    id: 34,
    parentId: 26,
    path: '/list/basic-list',
    title: '标准列表',
    name: 'BasicCard',
    component: '/list/basic-list',
    locale: 'menu.list.basic-list',
  },
  {
    id: 35,
    parentId: 28,
    path: '/profile/advanced',
    title: '高级详细页',
    name: 'ProfileAdvanced',
    component: '/profile/advanced/index',
    locale: 'menu.profile.advanced',
  },
  {
    id: 4,
    parentId: 3,
    title: '创建检测任务',
    component: 'RouteView',
    redirect: '/detection/malicious-domain-detection',
    path: '/detection/create-task',
    name: 'CreateDetectionTask',
    keepAlive: false,
    locale: 'menu.detection.create-task',
  },
  {
    id: 51,
    parentId: 4,
    title: '恶意域名检测',
    component: '/detection/malicious-domain-detection/index',
    path: '/detection/malicious-domain-detection',
    name: 'MaliciousDomainDetection',
    keepAlive: false,
    locale: 'menu.detection.malicious-domain-detection',
  },
  {
    id: 52,
    parentId: 4,
    title: '仿冒域名检测',
    component: '/detection/impersonation-domain-detection/index',
    path: '/detection/impersonation-domain-detection',
    name: 'ImpersonationDomainDetection',
    keepAlive: false,
    locale: 'menu.detection.impersonation-domain-detection',
  },
  {
    id: 53,
    parentId: 4,
    title: '恶意IP检测',
    component: '/detection/malicious-ip-detection/index',
    path: '/detection/malicious-ip-detection',
    name: 'MaliciousIpDetection',
    keepAlive: false,
    locale: 'menu.detection.malicious-ip-detection',
  },
  {
    id: 36,
    parentId: null,
    title: '个人页',
    icon: 'UserOutlined',
    component: 'RouteView',
    redirect: '/account/center',
    path: '/account',
    name: 'Account',
    locale: 'menu.account',
  },
  {
    id: 37,
    parentId: 36,
    path: '/account/center',
    title: '个人中心',
    name: 'AccountCenter',
    component: '/account/center',
    locale: 'menu.account.center',
  },
  {
    id: 38,
    parentId: 36,
    path: '/account/settings',
    title: '个人设置',
    name: 'AccountSettings',
    component: '/account/settings',
    locale: 'menu.account.settings',
  },
  {
    id: 39,
    parentId: 3,
    title: '分步表单',
    component: '/detection/step-detection/index',
    path: '/detection/step-detection',
    name: 'detectionStep',
    keepAlive: false,
    locale: 'menu.detection.step-detection',
  },
  {
    id: 40,
    parentId: 3,
    title: '我的任务',
    component: '/detection/mytask/index',
    path: '/detection/mytask',
    name: 'MyTask',
    keepAlive: false,
    locale: 'menu.detection.mytask',
  },
  {
    id: 41,
    parentId: 26,
    path: '/list/table-list',
    title: '查询表格',
    name: 'ConsultTable',
    component: '/list/table-list',
    locale: 'menu.list.consult-table',
  },
  {
    id: 42,
    parentId: 1,
    title: '监控页',
    component: '/dashboard/monitor',
    path: '/dashboard/monitor',
    name: 'DashboardMonitor',
    keepAlive: true,
    locale: 'menu.dashboard.monitor',
  },
  {
    id: 43,
    parentId: 1,
    title: '工作台',
    component: '/dashboard/workplace',
    path: '/dashboard/workplace',
    name: 'DashboardWorkplace',
    keepAlive: true,
    locale: 'menu.dashboard.workplace',
  },
  {
    id: 44,
    parentId: 26,
    path: '/list/crud-table',
    title: '增删改查表格',
    name: 'CrudTable',
    component: '/list/crud-table',
    locale: 'menu.list.crud-table',
  },
  {
    id: 48,
    parentId: 1,
    path: '/dashboard/attributes',
    component: '/dashboard/attributes',
    title: '属性分析',
    keepAlive: true,
    locale: 'menu.dashboard.attributes',
  },
  {
    id: 49,
    parentId: 1,
    path: '/dashboard/profile',
    component: '/dashboard/profile',
    title: '组织画像',
    keepAlive: true,
    locale: 'menu.dashboard.profile',
  },
  {
    id: 50,
    parentId: 3,
    title: '订阅与预警',
    path: '/detection/alert',
    component: '/detection/alert',
    name: 'detectionAlert',
    keepAlive: false,
    locale: 'menu.detection.alert',
  },
]

export default defineEventHandler((event) => {
  return {
    code: 200,
    msg: '获取成功',
    data: menuData,
  }
})
