from fastapi import APIRouter, Header

router = APIRouter()

@router.get("/api/menu")
async def get_menu(authorization: str | None = Header(None)):
    menu = [
        {
            "id": 1,
            "parentId": None,
            "title": "仪表盘",
            "icon": "DashboardOutlined",
            "component": "RouteView",
            "redirect": "/dashboard/monitor",
            "path": "/dashboard",
            "name": "Dashboard",
            "locale": "menu.dashboard",
        },
        {
            "id": 3,
            "parentId": None,
            "title": "检测任务",
            "icon": "FormOutlined",
            "component": "RouteView",
            "redirect": "/detection/create-task",
            "path": "/detection",
            "name": "detection",
            "locale": "menu.detection",
        },
        {
            "id": 9,
            "parentId": None,
            "title": "模型管理",
            "icon": "BarsOutlined",
            "component": "RouteView",
            "path": "/models",
            "redirect": "/models/menu1",
            "name": "ModleManagement",
            "locale": "menu.models",
        },
        {
            "id": 10,
            "parentId": 9,
            "title": "模型训练",
            "component": "/models/model-training/index",
            "path": "/models/model-training",
            "name": "ModelTraining",
            "keepAlive": True,
            "locale": "menu.models.model-training",
        },
        {
            "id": 11,
            "parentId": 9,
            "title": "模型市场",
            "component": "/models/model-market/index",
            "path": "/models/model-market",
            "keepAlive": True,
            "locale": "menu.models.model-market",
        },
        {
            "id": 12,
            "parentId": 9,
            "path": "/models/my-model",
            "title": "我的模型",
            "component": "/models/my-model/index",
            "keepAlive": True,
            "locale": "menu.models.my-model",
        },
        {
            "id": 4,
            "parentId": 3,
            "title": "创建检测任务",
            "component": "RouteView",
            "redirect": "/detection/malicious-domain-detection",
            "path": "/detection/create-task",
            "name": "CreateDetectionTask",
            "keepAlive": False,
            "locale": "menu.detection.create-task",
        },
        {
            "id": 51,
            "parentId": 4,
            "title": "恶意域名检测",
            "component": "/detection/malicious-domain-detection/index",
            "path": "/detection/malicious-domain-detection",
            "name": "MaliciousDomainDetection",
            "keepAlive": False,
            "locale": "menu.detection.malicious-domain-detection",
        },
        {
            "id": 52,
            "parentId": 4,
            "title": "仿冒域名检测",
            "component": "/detection/impersonation-domain-detection/index",
            "path": "/detection/impersonation-domain-detection",
            "name": "ImpersonationDomainDetection",
            "keepAlive": False,
            "locale": "menu.detection.impersonation-domain-detection",
        },
        {
            "id": 53,
            "parentId": 4,
            "title": "恶意IP检测",
            "component": "/detection/malicious-ip-detection/index",
            "path": "/detection/malicious-ip-detection",
            "name": "MaliciousIpDetection",
            "keepAlive": False,
            "locale": "menu.detection.malicious-ip-detection",
        },
        {
            "id": 36,
            "parentId": None,
            "title": "个人页",
            "icon": "UserOutlined",
            "component": "RouteView",
            "redirect": "/account/center",
            "path": "/account",
            "name": "Account",
            "locale": "menu.account",
        },
        {
            "id": 37,
            "parentId": 36,
            "path": "/account/center",
            "title": "个人中心",
            "name": "AccountCenter",
            "component": "/account/center",
            "locale": "menu.account.center",
        },
        {
            "id": 38,
            "parentId": 36,
            "path": "/account/settings",
            "title": "个人设置",
            "name": "AccountSettings",
            "component": "/account/settings",
            "locale": "menu.account.settings",
        },
        {
            "id": 40,
            "parentId": 3,
            "title": "我的任务",
            "component": "/detection/mytask/index",
            "path": "/detection/mytask",
            "name": "MyTask",
            "keepAlive": False,
            "locale": "menu.detection.mytask",
        },
        {
            "id": 42,
            "parentId": 1,
            "title": "监控页",
            "component": "/dashboard/monitor",
            "path": "/dashboard/monitor",
            "name": "DashboardMonitor",
            "keepAlive": True,
            "locale": "menu.dashboard.monitor",
        },
        {
            "id": 48,
            "parentId": 1,
            "path": "/dashboard/attributes",
            "component": "/dashboard/attributes",
            "title": "属性分析",
            "keepAlive": True,
            "locale": "menu.dashboard.attributes",
        },
        {
            "id": 49,
            "parentId": 1,
            "path": "/dashboard/profile",
            "component": "/dashboard/profile",
            "title": "组织画像",
            "keepAlive": True,
            "locale": "menu.dashboard.profile",
        },
        {
            "id": 50,
            "parentId": 3,
            "title": "订阅与预警",
            "path": "/detection/alert",
            "component": "/detection/alert",
            "name": "detectionAlert",
            "keepAlive": False,
            "locale": "menu.detection.alert",
        },
    ]

    return {"code": 200, "msg": "获取成功", "data": menu}
