from fastapi import APIRouter, Header

router = APIRouter()

@router.get("/api/menu")
async def get_menu(authorization: str | None = Header(None)):
    menu = [
        {
            "id": 2,
            "parentId": None,
            "title": "分析页",
            "icon": "DashboardOutlined",
            "component": "/dashboard/analysis",
            "path": "/dashboard/analysis",
            "name": "DashboardAnalysis",
            "keepAlive": True,
            "locale": "menu.dashboard.analysis",
        },
        {
            "id": 1,
            "parentId": None,
            "title": "仪表盘",
            "icon": "DashboardOutlined",
            "component": "RouteView",
            "redirect": "/dashboard/analysis",
            "path": "/dashboard",
            "name": "Dashboard",
            "locale": "menu.dashboard",
        },
        {
            "id": 3,
            "parentId": None,
            "title": "检测任务",
            "icon": "FormOutlined",
            "component": "RouteView",
            "redirect": "/detection/basic",
            "path": "/detection",
            "name": "detection",
            "locale": "menu.detection",
        },
        {
            "id": 9,
            "parentId": None,
            "title": "模型管理",
            "icon": "BarsOutlined",
            "component": "RouteView",
            "path": "/models",
            "redirect": "/models/menu1",
            "name": "ModleManagement",
            "locale": "menu.models",
        },
        {
            "id": 10,
            "parentId": 9,
            "title": "模型训练",
            "component": "/models/model-training/index",
            "path": "/models/model-training",
            "name": "ModelTraining",
            "keepAlive": True,
            "locale": "menu.models.model-training",
        },
        {
            "id": 11,
            "parentId": 9,
            "title": "模型市场",
            "component": "/models/model-market/index",
            "path": "/models/model-market",
            "keepAlive": True,
            "locale": "menu.models.model-market",
        },
        {
            "id": 12,
            "parentId": 9,
            "path": "/models/my-model",
            "title": "我的模型",
            "component": "/models/my-model/index",
            "keepAlive": True,
            "locale": "menu.models.my-model",
        },
        {
            "id": 15,
            "path": "/access",
            "component": "RouteView",
            "redirect": "/access/common",
            "title": "权限模块",
            "name": "Access",
            "parentId": None,
            "icon": "ClusterOutlined",
            "locale": "menu.access",
        },
        {
            "id": 16,
            "parentId": 15,
            "path": "/access/common",
            "title": "通用权限",
            "name": "AccessCommon",
            "component": "/access/common",
            "locale": "menu.access.common",
        },
        {
            "id": 17,
            "parentId": 15,
            "path": "/access/user",
            "title": "普通用户",
            "name": "AccessUser",
            "component": "/access/user",
            "locale": "menu.access.user",
        },
        {
            "id": 4,
            "parentId": 3,
            "title": "恶意性检测",
            "component": "/detection/malicious-detection/index",
            "path": "/detection/malicious-detection",
            "name": "MaliciousDetection",
            "keepAlive": False,
            "locale": "menu.detection.malicious-detection",
        },
        {
            "id": 36,
            "parentId": None,
            "title": "个人页",
            "icon": "UserOutlined",
            "component": "RouteView",
            "redirect": "/account/center",
            "path": "/account",
            "name": "Account",
            "locale": "menu.account",
        },
        {
            "id": 37,
            "parentId": 36,
            "path": "/account/center",
            "title": "个人中心",
            "name": "AccountCenter",
            "component": "/account/center",
            "locale": "menu.account.center",
        },
        {
            "id": 38,
            "parentId": 36,
            "path": "/account/settings",
            "title": "个人设置",
            "name": "AccountSettings",
            "component": "/account/settings",
            "locale": "menu.account.settings",
        },
        {
            "id": 40,
            "parentId": 3,
            "title": "我的任务",
            "component": "/detection/mytask/index",
            "path": "/detection/mytask",
            "name": "MyTask",
            "keepAlive": False,
            "locale": "menu.detection.mytask",
        },
        {
            "id": 42,
            "parentId": 1,
            "title": "监控页",
            "component": "/dashboard/monitor",
            "path": "/dashboard/monitor",
            "name": "DashboardMonitor",
            "keepAlive": True,
            "locale": "menu.dashboard.monitor",
        },
        {
            "id": 43,
            "parentId": 1,
            "title": "工作台",
            "component": "/dashboard/workplace",
            "path": "/dashboard/workplace",
            "name": "DashboardWorkplace",
            "keepAlive": True,
            "locale": "menu.dashboard.workplace",
        },
        {
            "id": 48,
            "parentId": 1,
            "path": "/dashboard/attributes",
            "component": "/dashboard/attributes",
            "title": "属性分析",
            "keepAlive": True,
            "locale": "menu.dashboard.attributes",
        },
        {
            "id": 49,
            "parentId": 1,
            "path": "/dashboard/profile",
            "component": "/dashboard/profile",
            "title": "组织画像",
            "keepAlive": True,
            "locale": "menu.dashboard.profile",
        },
        {
            "id": 50,
            "parentId": 3,
            "title": "订阅与预警",
            "path": "/detection/alert",
            "component": "/detection/alert",
            "name": "detectionAlert",
            "keepAlive": False,
            "locale": "menu.detection.alert",
        },
    ]

    access_menu_data = [
        {
            "id": 18,
            "parentId": 15,
            "path": "/access/admin",
            "title": "管理员",
            "name": "AccessAdmin",
            "component": "/access/admin",
            "locale": "menu.access.admin",
        },
    ]
    return {"code": 200, "msg": "获取成功", "data": menu}